export const CryptoApiBaseURL = 'https://api.coinmarketcap.com/v1/ticker/';
export const FETCH_CRYPTOCURRENCY_DATA = "FETCH_CRYPTOCURRENCY_DATA";
export const FETCH_CRYPTOCURRENCY_DATA_SUCESS = "FETCH_CRYPTOCURRENCY_DATA_SUCESS";
export const FETCH_CRYPTOCURRENCY_DATA_FAIL = "FETCH_CRYPTOCURRENCY_DATA_FAIL";
